# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a1debf156031117bd530b5f7c9a1a977"
name = "dev-custom-app"
application_url = "https://e2199cd0265524a67f0a87f2bff9e780.loophole.site"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,read_products,write_cart_transforms,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://e2199cd0265524a67f0a87f2bff9e780.loophole.site/auth/callback",
  "https://e2199cd0265524a67f0a87f2bff9e780.loophole.site/auth/shopify/callback",
  "https://e2199cd0265524a67f0a87f2bff9e780.loophole.site/api/auth/callback"
]

[product.metafields.app.bundle]
name = "Bundle"
description = "Bundle recipe: parent variant, component variants, fixed price"
type = "json"

  [product.metafields.app.bundle.access]
  admin = "merchant_read_write"
