api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "donat-custom-price"
type = "function"
uid = "dc96a244-3d28-fc10-e6b5-115630413fd4ea7513f3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
