query CartTransformRunInput {
  presentmentCurrencyRate
  shop {
    bundleConfig: metaobject(
      handle: { type: "$app:bundle_config", handle: "default-bundle" }
    ) {
      componentVariants: field(key: "component_variants") {
        jsonValue
      }
      parentVariant: field(key: "parent_variant") {
        value
      }
      fixedPrice: field(key: "fixed_price") {
        value
      }
      bundleTitle: field(key: "bundle_title") {
        value
      }
    }
  }
  cart {
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          title
          product {
            title
          }
        }
      }
    }
  }
}
